FROM node:20-alpine

WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm
RUN pnpm install turbo

EXPOSE 3000

# Use the mounted entrypoint script
CMD ["/bin/sh", "/app/docker-entrypoint.sh"]