services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - SKIP_ENV_VALIDATION=true
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_healthy

  # PostgreSQL as a replacement for Vercel PostgreSQL
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatbot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis as a replacement for Vercel KV
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MinIO as a replacement for Vercel Blob (S3-compatible storage)
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      # - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
      # - MINIO_SERVER_URL=http://localhost:9000
      - MINIO_DEFAULT_BUCKETS=chatbot-files:public
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # MinIO setup service - creates the bucket on startup
  createbuckets:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - MC_HOST_myminio=http://minioadmin:minioadmin@minio:9000
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc mb --ignore-existing myminio/chatbot-files;
      mc anonymous set download myminio/chatbot-files;
      mc anonymous set upload myminio/chatbot-files;
      echo 'MinIO bucket setup completed successfully';
      "
volumes:
  postgres_data:
  redis_data:
  minio_data: