services:
  postgres:
    image: postgres:14
    container_name: ai-chatbot-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: chatbot
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: ai-chatbot-minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/uploads;
      /usr/bin/mc policy set public myminio/uploads;
      exit 0;
      "

volumes:
  postgres_data:
  minio_data: